GET http://localhost:3000/api/alojamientos

###

POST http://localhost:3000/api/alojamientos
Content-Type: application/json

{
    "ciudad": "Madrid",
    "tipo_alojamiento": "Piso", 
    "tipo_habitacion": "Habitación compartida", 
    "direccion": "Calle Ancha, 123",
    "descripcion": "descripcion", 
    "img": "alguna", 
    "lavanderia": 1, 
    "cocina": 1, 
    "baño": 1, 
    "fecha_inicio": "2020-06-05", 
    "fecha_final": "2020-10-12", 
    "usuarios_id": 1
}

###

DELETE http://localhost:3000/api/alojamientos/10

###

PUT http://localhost:3000/api/alojamientos/9
Content-Type: application/json

{
    "ciudad": "Barcelona",
    "tipo_alojamiento": "Piso", 
    "tipo_habitacion": "Habitacion compartida", 
    "direccion": "Avenida Diagonal, 144",
    "descripcion": "descripcion", 
    "img": "alguna", 
    "lavanderia": 1, 
    "cocina": 1, 
    "baño": 1, 
    "fecha_inicio": "2020-06-05", 
    "fecha_final": "2020-10-12", 
    "usuarios_id": 1
}

###

GET http://localhost:3000/api/mensajes/1

###

POST http://localhost:3000/api/mensajes
Content-Type: application/json

{
    "texto": "Hola Pedro",
    "id_emisor": 1,
    "id_receptor": 2
}

###


###

GET http://localhost:3000/api/usuarios/1

###
POST http://localhost:3000/api/usuarios/registro
Content-Type: application/json

{
    "username": "pedrog9", 
    "password": "12345", 
    "nombre": "Pedro", 
    "apellidos": "Garcia",
    "email": "pedro@gmail.com", 
    "telefono": "616263646", 
    "edad": 12
}